#!/usr/bin/osascript
on run theArgs
	set theURL to item 1 of theArgs
	tell application "Google Chrome" to tell front window
		repeat with theIndex from 1 to count of tabs
			set theTab to tab theIndex
			if theTab's URL starts with theURL then
				set the active tab index to theIndex
				activate
				return
			end if
		end repeat
		open location theURL
		activate
	end tell
end run